<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TokenAuthentication\Module'                        => __DIR__ . '/Module.php',
    'TokenAuthentication\Controller\TokenController' => __DIR__ . '/src/TokenAuthentication/Controller/TokenController.php',
    'TokenAuthenticationTest\Framework\TestCase'        => __DIR__ . '/tests/TokenAuthentication/Framework/TestCase.php',
    'TokenAuthenticationTest\SampleTest'                => __DIR__ . '/tests/TokenAuthentication/SampleTest.php',
);
