<?php $token = isset($token) ? $token : new \TokenAuthentication\Mapper\Container() ?>
responseData:<?php echo $this->json(
		array('authenticationToken' => 
				array('token' => $token->getHash(), 
						'expires' => $this->webapidate($token->getCreationTime() + TokenAuthentication\Mapper\Token::TOKEN_EXPIRATION),
						'expiresTimestamp' => $token->getCreationTime() + TokenAuthentication\Mapper\Token::TOKEN_EXPIRATION
						)));